#' @param scen_name Name of the scenario. The directory containing all the model
#'  runs the scenario will be stored within a folder of this name.
#' @param nscen Which scenario is this. Integer value >=1
#' @param EM_name Name of a valid Stock Synthesis stock assessment model to use
#'  as an EM. If the value of EM_name is NULL and  \code{MS = "EM"}, then SSMSE
#'  will look for the estimation model in the path specified in EM_in_dir.
#'  or \code{NULL}.
#' @param use_SS_boot Should a bootstrapped data set generated by SS3 be used?
#'   Defaults to TRUE.
#' @param nyrs Number of years beyond the years included in the OM to run the
#'   MSE. A single integer value.
#' @param nyrs_assess The number of years between assessments. E.g., if an
#'   assessment is conducted every 3 years, put 3 here. A single integer value.
#'   (NOTE: we could make this more flexible by instead reading in a vector of
#'   assessment years, so users could specify irregular numbers of yrs between
#'   assessments.)
#' @param interim_struct A optional list of parameters to control an interim
#'  assessment with an example structure below, where Beta=a positive value
#'  that is inversely proportional to risk, MA_years= the number of years to
#'  average index observations of when calculating deviations, assess_freq=the
#'  number of years between full assessments during with an interim assessment
#'  will happen every year, and Index_weights is a vector of length n indexes
#'  that weights all indexes for multi index inference.
#'  ```
#'  interim_struct<-list(Beta = 1,
#'                       MA_years = 3,
#'                       assess_freq = 5,
#'                       Index_weights = rep(1, max(ref_index[, 3])))
#'  ```
