#' @param scen_name Name of the scenario. The directory containing all the model
#'  runs the scenario will be stored within a folder of this name.
#' @param nscen Which scenario is this. Integer value >=1
#' @param EM_name Name of a valid Stock Synthesis stock assessment model to use
#'  as an EM. If the value of EM_name is NULL and  \code{MS = "EM"}, then SSMSE
#'  will look for the estimation model in the path specified in EM_in_dir.
#'  or \code{NULL}.
#' @param use_SS_boot Should a bootstrapped data set generated by SS be used?
#'   Defaults to TRUE.
#' @param nyrs Number of years beyond the years included in the OM to run the
#'   MSE. A single integer value.
#' @param nyrs_assess The number of years between assessments. E.g., if an
#'   assessment is conducted every 3 years, put 3 here. A single integer value.
#'   (NOTE: we could make this more flexible by instead reading in a vector of
#'   assessment years, so users could specify irregular numbers of yrs between
#'   assessments.)
#' @param sample_struct A optional list including which years, seasons, and fleets
#'  should be  added from the OM into the EM for different types of data.
#'  If NULL, the data structure will try to be infered from the pattern found
#'  for each of the datatypes within the EM datafiles. Include this strucutre
#'  for the number of years to extend the model out. Note that the data should
#'  be specified using the list component names and column names as in would be
#'  used in \code{r4ss::SS_readdat()}. The run_SSMSE_iter function examples
#'  give an example of what this structure should be. Running the function
#'  create_sample_struct() will also produce a sample_struct object in the
#'  correct form. Can be NULL only when MS is not EM.
#' @param sample_struct_hist An optional list including which years should be
#'  sampled for the historical period for the data generated from the OM. If
#'  this is left as NULL, then the same sampling scheme will be used as in the
#'  OM's data file. If it is not NULL, then each year
#' @param interim_struct A optional list of parameters to control an interim
#'  assessment with an example structure below, where Beta=a positive value
#'  that is inversely proportional to risk, MA_years= the number of years to
#'  average index observations of when calculating deviations, assess_freq=the
#'  number of years between full assessments during with an interim assessment
#'  will happen every year, and Index_weights is a vector of length n indexes
#'  that weights all indexes for multi index inference.
#'  interim_struct<-list(Beta = 1,
#'                       MA_years = 3,
#'                       assess_freq = 5,
#'                       Index_weights = rep(1, max(ref_index[, 3])))
