# updates exiting bookdown for a repository
# deploys to a branch gh-pages in the same repository
name: call-update-bookdown
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
# this workflow runs on pushes to main or master
  push:
    branches: test-bookdown
  workflow_dispatch:
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/build-deploy-bookdown.yml@refresh-bookdown
    with:
      bookdown_input: 'inst/bookdown'
      bookdown_output_dir: '../../docs/manual'
      deployment_dir: 'docs'
